### PR TITLE
Refactoring of common Providers and AVPlayer base class into core

### PR DESCRIPTION
**Pull request by sweetpi**
All changes are untested, because I've no Kodi installation. So it would be cool if you test before publishing :)

### CODE REVIEW

**Comment by sweetpi** [comment]
@Fjuxx Any news? If you want, I can test an publish it, but I need push access to this repo and the npm module would be nice (https://docs.npmjs.com/cli/adduser).

**Comment by Fjuxx** [comment]
@sweetpi , i will check this.

As i must admit that i will be switching over to OpenHAB (yes i know it is like cheating)
But i was looking for something a bit more advanced, and OpenHAB seems the right call for that.

And i was missing a GUI (that is not only mobile based)

**Comment by Fjuxx** [comment]
@sweetpi , what commands do i need to enter to get you access? the link is only to add a new account.

Can i transfer all of npm and Github to you?

**Comment by sweetpi** [comment]
@Fjuxx Sorry wrong link, the right one: https://docs.npmjs.com/cli/owner

You need to run the following command for all packages:
```
npm owner add sweetpi pimatic-kodi
```

npm access is enough, I then fork all your repos into the pimatic organisation.

**Comment by sweetpi** [comment]
@Fjuxx Any news?

**Pull request merged**
